#cloud-config
autoinstall:
  version: 1

  early-commands:
    - ping -c1 8.8.8.8

  locale: en_US
  keyboard:
    layout: us
    variant: intl

  network:
    network:
      version: 2
      ethernets:
        enp3s0:
          dhcp4: true

  apt:
    primary:
      - arches: [default]
        uri: http://archive.ubuntu.com/ubuntu

  storage:
    layout:
      name: lvm

  identity:
    hostname: aliseo
    username: zhork
    password: "fa585d89c851dd338a70dcf535aa2a92fee7836dd6aff1226583e88e0996293f16bc009c652826e0fc5c706695a03cddce372f139eff4d13959da6f1f5d3eabe"

  ssh:
    install-server: false

  packages:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - build-essential
    - linux-headers-$(uname -r)
    - gcc
    - g++
    - make
    - git
    - unzip
    - neofetch
    - htop
    - curl
    - wget
    - feh
    - mpv
    - vlc
    - python3-pip
    - zsh
    - filezilla
    - qbittorrent

  user-data:
    disable_root: false

  late-commands:
    - sed -i 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=5/' /target/etc/default/grub
    - chroot /target update-grub
